# general colors
source = $HOME/.cache/wal/colors-hyprland.conf

# border colors
$active_border_color =  $color14 $color12
$inactive_border_color = rgba(595959aa)

# wallpaper path
$wallpaper_path = $HOME/Pictures/wallpapers/hollow-knight.png