# General colors
$first_color = rgba(9d7cffee)
$second_color = rgba(6b668aee)

# Border color
$active_border_color =  $first_color $second_color
$inactive_border_color = rgba(595959aa)

# Wallpaper path
$wallpaper_path = $HOME/Pictures/wallpapers/hollow-knight.png